name: Tests Laravel

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, dom, fileinfo, sqlite, pdo_sqlite
          coverage: none

      - name: Installer les dépendances
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Préparer le fichier .env
        run: cp .env.example .env

      - name: Générer la clé Laravel
        run: php artisan key:generate

      - name: Lancer les tests
        run: php artisan test
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
